name = "Concorde"
uuid = "df6a336b-a67f-4155-81fc-4f05fe893652"
authors = ["Changhyun Kwon <chkwon@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
