name = "Concorde"
uuid = "df6a336b-a67f-4155-81fc-4f05fe893652"
authors = ["Changhyun Kwon <chkwon@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TSPLIB = "b1c258e7-59ae-4b06-a547-f10871db1548"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
